title: Zane's Blog
description: 学习方法与知识管理
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 导航菜单
header_pages:
  - index.md
  - albums.md

# 文章链接格式
permalink: /:title/

# 站点设置
timezone: Asia/Shanghai
lang: zh-CN
